---
roles:
  - name: valkey
    src: https://github.com/mother-of-all-self-hosting/ansible-role-valkey.git
    scm: git
    version: main

collections:
  - name: amazon.aws
  - name: community.general
